### ISSUE TITLE
Samsung SM-T500 tablet - Serial number is not correctly retieved

### ISSUE THREAD

**Issue by PlanPc** [glpi-project/android-inventory-agent#334]
Testing with Samsung tablets, the information retrieved to server is not accurate about serial number.

All the rest seems great, but not serial number.

**Expected something like** : R9TNA7856EJ
**Server is getting as serial number, something like**: 7ab16cdcab605a9b

**Expected behavior**
Get the real serial number from Android 10 Samsung tablet

 - **GLPI Server** : Linux  PHP 7.3.16 Apache/2.2.34 (Unix) GLPI 9.5.3 (FusionInventory 9.5.0+1.0)
 - **OS**: Android 10
 - **Browser** not applicable
 - **Version** GLPI AGENT: 1.0.0 BUILD 39263 (Built on Tue Jan 07 11:29:30 2020 Last commit 41a30eb)

**Smartphone**
 - **Device**: Samsung SM-T500 tablet
 - **OS**: Android 10
 - **Browser** not applicable
 - **Version** GLPI AGENT: 1.0.0 BUILD 39263 (Built on Tue Jan 07 11:29:30 2020 Last commit 41a30eb)

**Comment by stonebuzz** [comment]
Hi @PlanPc 

As of Android 10 (API level 29), [there's no way for non-system and non-carrier apps to get the device's serial number](https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids), not even by calling the new Build.getSerial() method with the READ_PHONE_STATE permission, since per the docs it'll always either return Build.UNKNOWN (API < 29) or throw a SecurityException (API >= 29). This means that our mehod to get "official" serial might not work on some devices running Android 10+, due to changes in the Android OS itself and AFAIK there's no workaround (for the moment).

To avoid any security changes from Google, the Android agent already uses the Secure.ANDROID_ID as a last resort (if other methods return an empty serial number)

ANDROID_ID is the best way to manage unique ID from device actually because is not device owner app.

Maybe we should improve the agent to make it (owner app) like MDM

Best regards

**Comment by PlanPc** [comment]
Thank you very much @stonebuzz 

I thought it could be a general or specific problem of samsung devices or android version, etc., but I already see that it is a limitation of the Android system itself. In this case I will see how I can identify each device in another way. 

It is a pity that the operating system is an impediment to such good software.

Many thanks for everything.


> Hi @PlanPc
> 
> As of Android 10 (API level 29), [there's no way for non-system and non-carrier apps to get the device's serial number](https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids), not even by calling the new Build.getSerial() method with the READ_PHONE_STATE permission, since per the docs it'll always either return Build.UNKNOWN (API < 29) or throw a SecurityException (API >= 29). This means that our mehod to get "official" serial might not work on some devices running Android 10+, due to changes in the Android OS itself and AFAIK there's no workaround (for the moment).
> 
> To avoid any security changes from Google, the Android agent already uses the Secure.ANDROID_ID as a last resort (if other methods return an empty serial number)
> 
> ANDROID_ID is the best way to manage unique ID from device actually because (agent) is not device owner app.
> 
> Maybe we should improve the agent to make it (owner app) like MDM
> 
> Best regards
